### ISSUE TITLE
нельзя продать яблоки

### ISSUE THREAD

**Issue by hekkiii** [aleksandr-mishukhin/ecommerce#1]
![akhuennye_yabloki](https://github.com/aleksandr-mishukhin/ecommerce/assets/117893294/3480d15f-7ec0-41fb-9d74-9b556d2f7fd5)
Не могу продать в программе яблоки, что делать?

**Comment by aleksandr-mishukhin** [comment]
Такое не продаем.

![image](https://github.com/aleksandr-mishukhin/ecommerce/assets/144798712/adbaeb62-b2c4-4461-b691-48e28e43ac58)
